const AppConstants = {
    API_LOGIN_FAIL: "API_LOGIN_FAIL",
    somethingwentwrong: "Something Went Wrong",
    API_LOGIN_ERROR: "API_USER_ERROR",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    CREATE_OR_EDIT_USER_SUCCESS: "API_CREATE_OR_UPDATE_USER_SUCCESS",
    CREATE_OR_EDIT_USER_LOAD: "CREATE_OR_EDIT_USER_LOAD",
    GET_USER_LOAD: "GET_USER_LOAD",
}

export default AppConstants